language: php
php:
- 7.1
- 7.2
env:
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
- vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
- vendor/bin/phpcs --standard=PSR2 ./src
after_script:
- php vendor/bin/coveralls -v
notifications:
  slack:
    rooms:
      secure: qDZGpZEOrZmtBgvVxczEJKHZtyX69IGN2+EDeHKrBZjpn/2TWMiWfOupAKcHzlk49bZbxD+0RYcnjW9vqwXYUJVqAoSwzC0jydajgGFlMdx6OTTM7yAv+Rn1uon+Xop9xTmFZMBayhplj3N6d1Na3s7AnQFEfJc66p+qd+eVR42uKTpL4rbzJEO+Gr0T5fQNdOB5/to35VIcl7x5AnmBMZdq/j6BOKFRLrxFofptny7iR0U4wtIYcgOx3R1ZdvVu9mVytFbNEJYWAHcgcxAOChCNYh3D57KvP3WrupB+B0V18ymIIetDZvWwC48TFpdN1DZ2nF59UdeiHwLCcO2anm9GTgoPi7lv0RdZw8h8n8eNHdEYGWSZny6YJR/Kku2E2rYeazlqlDoohq1GQIjBwxOQRre2LFqz4qHK/XInB10eG13RodgOF3OSDjOswGA3CiQb6xGKYt966c9YtB7JP0wiHvYkQt/VOtTtz6wz/q/5fE9e2E0dJNxrKeAOG1VDz1gCOy2QdF2x6SWeGj7TPQMlV48lle2rHM9dd8qstqSzob4oMsMt3A9/nQkgSUCtVNiDMIwdrEPMMqOuLtc8pOf7A2Yl4ci81+9HUKsxKKMgR5l9FEtVIPTzCWZH40A8xxRHHWFIB/IB+WazN7lu+6cojppu7Rgh/sMAH9Qswo8=
